### PR TITLE
Solve pitch bug

### LINKED ISSUE #27: Parse stereo sound effects as actually stereo

### PR DESCRIPTION
**Pull request by default-username-852**
This resolves #27. The issue was that we assumed that the sound output was stereo. Now, we check whether the output is stereo or not when parsing the audio. In the future, we probably want to prefer stereo audio, and fall back to mono if stereo isn't available. Currently, mumd always outputs audio as mono (at least on my machine).

### CODE REVIEW

File: mumd/src/audio.rs [hunk 1]
```diff
@@ -231,12 +231,18 @@ impl Audio {
...
+                    2 => Box::new(samples.into_iter()),
+                    _ => unimplemented!() // TODO handle gracefully (this might not even happen)
+                };
+                let mut signal = signal::from_interleaved_samples_iter::<_, [f32; 2]>(iter);
                 let interp = Linear::new(signal.next(), signal.next());
                 let samples = signal
                     .from_hz_to_hz(interp, spec.sample_rate as f64, SAMPLE_RATE as f64)
                     .until_exhausted()
-                    .collect::<Vec<_>>();
+                    .flat_map(|e| if output_config.channels == 1 { vec![e[0]] } else { e.to_vec() })
```
Comment (sornas) [inline mumd/src/audio.rs:244]: I guess this means mono takes only the left channel? I say add a comment if that's the case, it's a kinda weird thing.

**Review by sornas — APPROVED** [review]
Nice work

File: mumd/src/audio.rs (hunk 1 above)
Comment (default-username-852) [reply mumd/src/audio.rs:244]: It takes one of the channels (might be left, don't really know) if outputting mono audio. Maybe we'd want to do some blending of the channels, but sound effects aren't really stereo, so I don't know.
